//---------------------------------------------------------------------------

#ifndef SVK2H
#define SVK2H
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ExtCtrls.hpp>
//---------------------------------------------------------------------------
class TForm1 : public TForm
{
__published:	// IDE-managed Components
        TGroupBox *GroupBox1;
        TComboBox *ComboBox1;
        TComboBox *ComboBox2;
        TButton *Button1;
        TLabel *Label1;
        TLabel *Label2;
        TButton *Button2;
        TButton *Button3;
        TButton *Button4;
        TGroupBox *GroupBox2;
        TLabel *Label3;
        TEdit *Edit1;
        TEdit *Edit2;
        TLabel *Label5;
        TLabel *Label6;
        TLabel *Label4;
        TEdit *Edit3;
        TLabel *Label7;
        TEdit *Edit4;
        TLabel *Label8;
        TEdit *Edit5;
        TGroupBox *GroupBox3;
        TLabel *Label9;
        TEdit *Edit6;
        TLabel *Label10;
        TEdit *Edit7;
        TEdit *Edit8;
        TEdit *Edit9;
        TEdit *Edit10;
        TEdit *Edit11;
        TEdit *Edit12;
        TEdit *Edit13;
        TEdit *Edit14;
        TEdit *Edit15;
        TEdit *Edit16;
        TEdit *Edit17;
        TEdit *Edit18;
        TEdit *Edit19;
        TEdit *Edit20;
        TEdit *Edit21;
        TEdit *Edit22;
        TEdit *Edit23;
        TEdit *Edit24;
        TEdit *Edit25;
        TEdit *Edit26;
        TEdit *Edit27;
        TEdit *Edit28;
        TEdit *Edit30;
        TEdit *Edit31;
        TEdit *Edit32;
        TEdit *Edit33;
        TEdit *Edit34;
        TEdit *Edit36;
        TEdit *Edit37;
        TEdit *Edit38;
        TEdit *Edit40;
        TEdit *Edit42;
        TEdit *Edit43;
        TEdit *Edit44;
        TEdit *Edit45;
        TEdit *Edit46;
        TEdit *Edit48;
        TEdit *Edit49;
        TEdit *Edit50;
        TLabel *Label11;
        TLabel *Label12;
        TLabel *Label13;
        TLabel *Label14;
        TLabel *Label15;
        TLabel *Label16;
        TLabel *Label17;
        TLabel *Label18;
        TLabel *Label19;
        TLabel *Label20;
        TEdit *Edit51;
        TEdit *Edit52;
        TEdit *Edit53;
        TEdit *Edit55;
        TEdit *Edit56;
        TEdit *Edit57;
        TEdit *Edit58;
        TEdit *Edit60;
        TEdit *Edit61;
        TEdit *Edit62;
        TEdit *Edit63;
        TEdit *Edit64;
        TEdit *Edit65;
        TEdit *Edit67;
        TEdit *Edit68;
        TEdit *Edit69;
        TEdit *Edit70;
        TEdit *Edit71;
        TEdit *Edit73;
        TLabel *Label21;
        TEdit *Edit72;
        TLabel *Label22;
        TEdit *Edit29;
        TLabel *Label23;
        TGroupBox *GroupBox4;
        TCheckBox *CheckBox1;
        TLabel *Label24;
        TEdit *Edit35;
        TCheckBox *CheckBox2;
        TCheckBox *CheckBox3;
        TCheckBox *CheckBox4;
        TGroupBox *GroupBox5;
        TLabel *Label25;
        TLabel *Label26;
        TLabel *Label27;
        TLabel *Label28;
        TLabel *Label29;
        TCheckBox *CheckBox5;
        TCheckBox *CheckBox7;
        TCheckBox *CheckBox8;
        TCheckBox *CheckBox9;
        TCheckBox *CheckBox10;
        TCheckBox *CheckBox11;
        TCheckBox *CheckBox12;
        TCheckBox *CheckBox6;
        TCheckBox *CheckBox14;
        TCheckBox *CheckBox15;
        TCheckBox *CheckBox16;
        TCheckBox *CheckBox17;
        TCheckBox *CheckBox18;
        TCheckBox *CheckBox19;
        TCheckBox *CheckBox20;
        TCheckBox *CheckBox21;
        TCheckBox *CheckBox23;
        TCheckBox *CheckBox24;
        TCheckBox *CheckBox25;
        TCheckBox *CheckBox26;
        TCheckBox *CheckBox27;
        TCheckBox *CheckBox28;
        TCheckBox *CheckBox29;
        TCheckBox *CheckBox30;
        TCheckBox *CheckBox32;
        TCheckBox *CheckBox33;
        TCheckBox *CheckBox34;
        TCheckBox *CheckBox35;
        TCheckBox *CheckBox36;
        TCheckBox *CheckBox37;
        TCheckBox *CheckBox38;
        TCheckBox *CheckBox39;
        TLabel *Label30;
        TGroupBox *GroupBox6;
        TLabel *Label31;
        TEdit *Edit41;
        TLabel *Label32;
        TLabel *Label33;
        TLabel *Label34;
        TLabel *Label35;
        TEdit *Edit47;
        TEdit *Edit54;
        TEdit *Edit59;
        TEdit *Edit66;
        TEdit *Edit74;
        TEdit *Edit75;
        TEdit *Edit76;
        TLabel *Label36;
        TLabel *Label37;
        TLabel *Label38;
        TGroupBox *GroupBox7;
        TEdit *Edit78;
        TLabel *Label39;
        TLabel *Label40;
        TEdit *Edit77;
        TRadioGroup *RadioGroup1;
        TRadioButton *RadioButton1;
        TRadioButton *RadioButton2;
        TRadioButton *RadioButton3;
        TRadioButton *RadioButton4;
        TButton *Button6;
  TLabel *Label41;
  TLabel *Label42;
  TEdit *Edit79;
  TEdit *Edit80;
  TEdit *Edit81;
  TEdit *Edit82;
  TLabel *Label43;
  TLabel *Label44;
  TLabel *Label45;
  TTimer *Timer1;
  TEdit *Edit83;
  TLabel *Label46;
  TCheckBox *CheckBox22;
  TCheckBox *CheckBox40;
  TCheckBox *CheckBox42;
  TCheckBox *CheckBox44;
  TButton *Button5;
  TButton *Button7;
  TButton *Button8;
  TLabel *Label47;
        void __fastcall Button2Click(TObject *Sender);
  void __fastcall Button4Click(TObject *Sender);
  void __fastcall Button3Click(TObject *Sender);
  void __fastcall Timer1Timer(TObject *Sender);
  void __fastcall Button8Click(TObject *Sender);
  void __fastcall Button5Click(TObject *Sender);
  void __fastcall Button7Click(TObject *Sender);
private:	// User declarations
public:		// User declarations
        __fastcall TForm1(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TForm1 *Form1;
//---------------------------------------------------------------------------
#endif
